services:
  atcoder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atcoder
    # Windowsのフォルダをコンテナ内の /app に同期する
    volumes:
      - .:/app
    # コンテナを起動しっぱなしにする設定
    tty: true
    # 再起動設定（PC再起動時などは手動でupするなら "no" でOK）
    restart: "no"
